server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: ${APP_NAME:solicitudes}
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui"
    try-it-out-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200,http://localhost:8080,http://localhost:8081} #http://localhost:4200
routes:
  paths:
    solicitud: "/api/v1/solicitud"
adapters:
  r2dbc:
    host: ${SPRING_R2DBC_URL:localhost} #localhost
    port: ${SPRING_R2DBC_PORT:5432} #5432
    database: ${SPRING_R2DBC_DB_NAME:Autenticacion} #Autenticacion
    schema: ${SPRING_R2DBC_SCHEMA:crediya} #crediya
    username: ${SPRING_R2DBC_USERNAME:postgres} #postgres
    password: ${SPRING_R2DBC_PASSWORD:root} #root
adapter:
  restconsumer:
    timeout: 50000
    url: ${AUTH_BASE_URL:http://localhost:8080/api/v1} # http://localhost:8080/api/v1
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"