BEGIN;

-- 1) Crear esquema
CREATE SCHEMA IF NOT EXISTS crediya;

-- 2) Tabla: estados
CREATE TABLE IF NOT EXISTS crediya.estados (
    id_estado     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre        VARCHAR(100)  NOT NULL UNIQUE,
    descripcion   VARCHAR(255)
);

-- 3) Tabla: tipo_prestamo
CREATE TABLE IF NOT EXISTS crediya.tipo_prestamo (
    id_tipo_prestamo      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR(100)  NOT NULL UNIQUE,
    monto_minimo          NUMERIC(15,2) NOT NULL,
    monto_maximo          NUMERIC(15,2) NOT NULL,
    tasa_interes          NUMERIC(5,2)  NOT NULL,   -- porcentaje (ej: 12.50)
    validacion_automatica BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_tipo_prestamo_montos CHECK (monto_minimo >= 0 AND monto_maximo >= monto_minimo),
    CONSTRAINT ck_tipo_prestamo_tasa   CHECK (tasa_interes >= 0)
);
-- 3) Tabla: solicitud
CREATE TABLE IF NOT EXISTS crediya.solicitud (
    id_solicitud      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto             NUMERIC(15,2) NOT NULL,
    plazo             INTEGER       NOT NULL,            -- en meses
    email             VARCHAR(254)  NOT NULL,
    id_estado         BIGINT        NOT NULL,            -- FK -> crediya.estados(id_estado)
    id_tipo_prestamo  BIGINT        NOT NULL,            -- FK -> crediya.tipo_prestamo(id_tipo_prestamo)
    id_usuario        BIGINT        NOT NULL,            -- FK -> crediya.usuario(id_usuario)

    CONSTRAINT ck_solicitud_monto CHECK (monto >= 0),
    CONSTRAINT ck_solicitud_plazo CHECK (plazo > 0),

    CONSTRAINT fk_solicitud_estado
        FOREIGN KEY (id_estado)
        REFERENCES crediya.estados (id_estado)
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,

    CONSTRAINT fk_solicitud_tipo
        FOREIGN KEY (id_tipo_prestamo)
        REFERENCES crediya.tipo_prestamo (id_tipo_prestamo)
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

-- Índices para las FKs
CREATE INDEX IF NOT EXISTS idx_solicitud_id_estado
    ON crediya.solicitud (id_estado);

CREATE INDEX IF NOT EXISTS idx_solicitud_id_tipo_prestamo
    ON crediya.solicitud (id_tipo_prestamo);

 --Semillas de estados:
 INSERT INTO crediya.estados (nombre, descripcion) VALUES
   ('PENDIENTE DE REVISIÓN','Solicitud registrada, en evaluación'),
   ('APROBADO','Solicitud aprobada'),
   ('RECHAZADO','Solicitud rechazada'),
   ('REVISION MANUAL','Solicitud registrada y pendiente de ser revisada por un a, en evaluación');

INSERT INTO crediya.tipo_prestamo
  (nombre, monto_minimo, monto_maximo, tasa_interes, validacion_automatica)
VALUES
  ('Microcrédito',        100000.00,  5000000.00,  24.50, TRUE),
  ('Consumo',             500000.00, 80000000.00, 19.90, FALSE),
  ('Educativo',           200000.00, 20000000.00, 12.00, TRUE);

COMMIT;